apiVersion: v1
kind: Service
metadata:
  name: my-service
spec:
  type: NodePort
  selector:
    app: webpass
  ports:
    - port: 80
      targetPort: 80
      nodePort: 30000
  externalIPs:
    - 192.168.122.10
